---
#
# Solve common issues
#

- name: Unblock bluetooth
  shell: "rfkill unblock bluetooth"

- name: Restart bluetooth service
  service: name=bluetooth state=restarted

- name: Append -E flag to bluetooth service
  lineinfile: dest=/lib/systemd/system/bluetooth.service regexp="ExecStart=" line="ExecStart=/usr/lib/bluetooth/bluetoothd -E"
